### PR TITLE
Newsweek Clone 

### PR DESCRIPTION
**Pull request by tGodson**
This is a clone of the Newsweek magazine bootstrap project.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @tGodson, great job with an amazing effort :+1: However, before we proceed and approve the project, we need to work on the comments below:
- Kindly enable stickler for the repo, visit stickler-ci and enable stickler to check for CSS errors
- Kindly fix the main nav links
```Currently```
nav
```Original```
nav1
```Mobile screen 798px```
- Kindly compare the layout to the original and make the necessary fix, the heroes of the pandemic takes the full width as in the top story
```Currently```
b
```Original```
b1
- ```More stories section```
```Currently```
more1
```Original```
more
- The width of the editors pick takes the full width, let us compare to the original up to subscribe section
```Currently```
ed
```Original```
ed1
```Currently```
sub
```Original```
sub1
```Currently```
nw
```Original```
nw1
- Kindly delete commented code in our CSS files
- Also since this project focus is mainly using a bootstrap CSS framework, let use bootstrap classes like ``` d-none``` instead of ```display: none```. Let use more of Bootstrap CSS classes and reduce the custom CSS
- Let us apply the DRY rule to our CSS  file also let us avoid using "ids" for styling

Kindly make these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

**Comment by lucasmazo32** [comment]
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. For the project to get approved kindly implement these changes:

## Required changes:

- [x] In the original webpage, you have a change of layout at 768px (Medium or -md in bootstrap), and in it, the Featured stories are right below the Top stories. Kindly fix that. 

> Original
image

- [x] Please erase the comments in your CSS file. Lines 65 and 263.

You are close, please implement these changes and submit them for another code review!

### Happy coding! :computer:

## Lucas Mazo

**Comment by santiago-dev96** [comment]
## Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Changes required :no_good_man:
I can't review this project because the repository is not professional.

Friendly reminder: You should make sure that your repo looks professional before review. Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

You can reach me out on Slack as **srodrig**. Have a nice day! :wave:.

**Review by serdg0 — APPROVED** [review]
Congratulations @tGodson !! :100: 

Feel free to merge to master.

Keep the good work in your next project!

Happy Coding! :computer: :nerd_face:

**Pull request merged**
